### PR TITLE
Github actions: run tests and builds

### PR DESCRIPTION
**Pull request by harlantwood**
Set up basic CI:
- run `yarn test` in server and common
  - run `yarn build` in common in order to run server tests
- run `yarn build` in server and cli 

Tests are passing on my branch: https://github.com/harlantwood/adx/actions?query=branch%3Aci

### CODE REVIEW

**Comment by harlantwood** [comment]
I wanted to start off CI simply, but some other thoughts for future PRs:
- Could run on mac runner as well as unix (or even try windows runner!)
- Could limit runs to changes in relevant directories, plus relevant CI files, plus maybe root package.json/yarn.lock
- Would be cool to turn this script into an integration test... https://github.com/bluesky-social/adx/blob/main/README.md#%EF%B8%8F-quick-use

**Comment by dholms** [comment]
Sweet this seems reasonable to me 👍 

Yup let's keep this pretty simple for now. The server tests right now are basically integration tests & actually a bit more rigorous than the quick use script.

Thanks for putting this together!

**Review by dholms — APPROVED** [review]

**Comment by pfrazee** [comment]
Oh hold up, @AaronGoldman brought up a concern here - are we protecting against drive-by PRs that automatically trigger CI?

**Comment by harlantwood** [comment]
> Oh hold up, @AaronGoldman brought up a concern here - are we protecting against drive-by PRs that automatically trigger CI?

@pfrazee admins can adjust those settings here:
https://github.com/bluesky-social/adx/settings/actions

**Comment by pfrazee** [comment]
Ah. I dont have admin control! @dholms do you?

**Comment by harlantwood** [comment]
> Thanks for putting this together!

My pleasure. 😄 Awesome project BTW, nice work!

**Comment by dholms** [comment]
> Ah. I dont have admin control! @dholms do you?

gave you admin control @pfrazee

**Comment by pfrazee** [comment]
Thanks. I set it to always require approval in the context of outside PRs. I dont have a lot of experience with GH Actions so other folks should review

**Pull request merged**
